sudo: false

language: php

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  directories:
    - vendor
    - node_modules

install:
  - npm install -g grunt-cli
  - npm install
  - bash bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION

script:
  - grunt scripts
  - phpunit
